name: Angular Ci Cd

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run:  npm run stage-build && cp dist/angular-ci-cd/index.html dist/angular-ci-cd/404.html

      # - name: Lint
      #   run: npm run lint

      # - name: Test
      #   run: npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: stage # The branch the action should deploy to.
          folder: dist/angular-ci-cd # The folder the action should deploy.
